version: '3'

services:
  backend:
    image: node:18
    working_dir: /app/backend
    command: yarn dev
    volumes:
      - ./backend:/app/backend
      - ./node_modules:/app/backend/node_modules
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
    networks:
      - default
    ports: 
      - "3000:3000"
    environment:
      - THIRD_PARTY_URL=http://third-party:3001

  frontend:
    image: node:18
    working_dir: /app/frontend
    command: yarn dev
    volumes:
      - ./frontend:/app/frontend
      - ./node_modules:/app/node_modules
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
    depends_on:
      - backend
    networks:
      - default
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://third-party:3001

  third-party:
    image: node:18
    working_dir: /app
    command: yarn dev
    volumes:
      - ./third-party:/app
      - ./node_modules:/app/node_modules
      - ./tsconfig.json:/tsconfig.json
    depends_on:
      - backend
    networks:
      - default
    ports:
      - "3001:3001"
    environment:
      - BACKEND_URL=http://backend:3000

networks:
    default:
        driver: bridge